# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7cad73e800b26c1b60a623de20505768ab225bab70aa142f79580cc7d7661ccdeaaaee8474c902714b8d81957765a57e2fc653686e4e5ed960f01bef50fe48c

test:
  secret_key_base: 8348fb23c7910198ef3dbf6c7328b34f727df39fa4e986389e9d492514bdb793d66cd9d4fea6ad685ccd8855dab64792af112b3cb7202fe60077eb7c8c4d273e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
